var WatuPRO={};var WatuPROSettings=[];WatuPRO.forceSubmit=false;WatuPRO.confirmOnSubmit=false;WatuPRO.dontPromtUnanswered=false;WatuPRO.dontPromtNotlastpage=false;WatuPRO.dontScroll=false;WatuPRO.dontScrollStart=false;WatuPRO.inCategoryPages=false;WatuPRO.jsTimeDiff=null;WatuPRO.timerAdjustedBySchedule=false;WatuPRO.currentDecade=0;WatuPRO.currentAnswersDecade=1;WatuPRO.perDecade=10;WatuPRO.progressBarMode='pages';WatuPRO.qArr=[];WatuPRO.changeQCat=function(item){if(item.value=="-1")jQuery("#newCat").show();else jQuery("#newCat").hide();}
WatuPRO.current_question=1;WatuPRO.total_questions=0;WatuPRO.mode="show";WatuPRO.fullTimeLimit=0;WatuPRO.checkAnswer=function(e,questionID){this.answered=false;var questionID=questionID||WatuPRO.qArr[WatuPRO.current_question-1];this.answered=this.isAnswered(questionID);if(!this.answered&&e){if(jQuery.inArray(questionID,WatuPRO.requiredIDs)!=-1){if(jQuery('.watupro-minsel-id-'+questionID).length>0){let minSels=WatuPRO.countMinSels(questionID);let minSelMsg=watupro_i18n.min_sel_msg.replace('{{min-selections}}',minSels);alert(minSelMsg);}
else alert(watupro_i18n.answering_required);return false;}
if(!this.dontPromtUnanswered&&!confirm(watupro_i18n.did_not_answer)){e.preventDefault();e.stopPropagation();return false;}}
return true;}
WatuPRO.isAnswered=function(questionID){if(typeof(questionID)=='undefined')return true;var isAnswered=false;if(questionID==0)return true;var answerType=jQuery('#answerType'+questionID).val();if(answerType=='radio'&&jQuery('#dropdowQuestion-'+questionID).length){if(jQuery('#dropdowQuestion-'+questionID).val()=='')return false;return true;}
if(answerType=='slider')return true;if(answerType=='sort')return true;if(answerType=='matrix'||answerType=='nmatrix'){isAnswered=true;jQuery('.answerof-'+questionID).each(function(){if(jQuery(this).val()=='')isAnswered=false;});if(isAnswered)return true;}
if(answerType=='textarea'){if(jQuery('.watupro-file-upload-required-'+questionID).length>0&&jQuery('.watupro-file-upload-required-'+questionID).first().val()=='')return false;if(jQuery('.hide-textarea-'+questionID).length>0)return true;if(jQuery('#textarea_q_'+questionID).attr('class')=='wp-editor-area'){if(tinyMCE.get('textarea_q_'+questionID).getContent())return true;}
else if(jQuery("#textarea_q_"+questionID).val()!="")return true;let audioData=jQuery("#watuproAudioData"+questionID).val();if(audioData&&audioData!=="{}")return true;return false;}
let numChks=0;jQuery(".answerof-"+questionID).each(function(i){if(answerType=='radio'||answerType=='checkbox'){if(this.checked){isAnswered=true;numChks++;}}
if(answerType=='gaps'){if(this.value)isAnswered=true;}});if(jQuery('.watupro-minsel-id-'+questionID).length>0){let minSels=WatuPRO.countMinSels(questionID);if(jQuery('.watupro-minsel-id-'+questionID+':checked').length<minSels)isAnswered=false;}
return isAnswered;}
WatuPRO.countMinSels=function(questionID){let minSels=1;let elementClasses=jQuery('.watupro-minsel-id-'+questionID+':first').attr('class').split(' ');for(let i=0;i<elementClasses.length;i++){let match=elementClasses[i].match(/^watupro-min-selections-(\d+)$/);if(match){minSels=match[1];break;}}
return minSels;}
WatuPRO.nextQuestion=function(e,dir,gotoQuestion){var dir=dir||'next';var gotoQuestion=gotoQuestion||0;if(dir=='next'){if(!WatuPRO.checkAnswer(e))return false;}
else WatuPRO.checkAnswer(null);this.stopAudios();if(!WatuPRO.dontScroll&&dir!='goto'&&jQuery(document).scrollTop()>250){jQuery('html, body').animate({scrollTop:jQuery('#watupro_quiz').offset().top-100},100);}
if(!this.inCategoryPages)jQuery("#question-"+WatuPRO.current_question).hide();questionID=jQuery("#qID_"+WatuPRO.current_question).val();if(dir=='next')WatuPRO.current_question++;else if(dir=='goto')WatuPRO.current_question=gotoQuestion;else WatuPRO.current_question--;jQuery("#question-"+WatuPRO.current_question).show();this.hilitePage(WatuPRO.current_question,this.answered);var memQuestionID=WatuPRO.qArr[WatuPRO.current_question-1];if(jQuery('#watuproMemory'+memQuestionID).length>0&&jQuery('#watuproMemory'+memQuestionID).is(":visible")){WatuPRO.showingMemory(memQuestionID);}
else jQuery('.watupro_buttons').show();if(WatuPRO.total_questions<=WatuPRO.current_question){jQuery("#next-question").addClass("watupro-hidden");jQuery('#action-button').show();if(jQuery('#WTPReCaptcha').length)jQuery('#WTPReCaptcha').show();if(jQuery('#WatuPROTextCaptcha').length)jQuery('#WatuPROTextCaptcha').show();}
else{jQuery("#next-question").removeClass("watupro-hidden");if(jQuery('#WTPReCaptcha').length)jQuery('#WTPReCaptcha').hide();if(jQuery('#WatuPROTextCaptcha').length)jQuery('#WatuPROTextCaptcha').hide();}
WatuPRO.maybeHideNext();if(WatuPRO.current_question>1&&!this.inCategoryPages)jQuery('#prev-question').removeClass("watupro-hidden");else jQuery('#prev-question').addClass("watupro-hidden");if(jQuery('#questionWrap-'+WatuPRO.current_question).is(':hidden')){jQuery('#liveResultBtn').hide();}else{if(jQuery('#liveResultBtn').length)jQuery('#liveResultBtn').show();}
if(!this.inCategoryPages)WatuPRO.progressBar(WatuPRO.current_question,WatuPRO.exam_id);jQuery.event.trigger({type:'watupro-custom',subtype:'show_question',question_id:questionID,qnum:WatuPRO.current_question});if(!WatuPRO.store_progress||!e)return false;var data={"exam_id":WatuPRO.exam_id,"question_id":questionID,'action':'watupro_store_details','watupro_questions':jQuery('#quiz-'+WatuPRO.exam_id+' input[name=watupro_questions]').val(),"current_question":WatuPRO.current_question};data=WatuPRO.completeData(data);jQuery.post(WatuPRO.siteURL,data,function(msg){if(jQuery('#watuproEvaluateOnTheFly'+WatuPRO.exam_id).length&&WatuPROIntel)WatuPROIntel.runTimeLogic(msg);});}
WatuPRO.goto=function(e,j,qPaginator){qPaginator=qPaginator||null;if(this.inCategoryPages&&!e){this.curCatPage=this.current_question;curQuesID=jQuery('#catDiv'+this.curCatPage+' div.watu-question').first().attr('id');parts=curQuesID.split('-');WatuPRO.current_question=parseInt(parts[1]);j=WatuPRO.current_question;}
this.nextQuestion(e,'goto',j);var questionID=jQuery("#qID_"+WatuPRO.current_question).val();var isAnswered=this.isAnswered(questionID);this.hilitePage(j,isAnswered);jQuery('.watupro-paginator-wrap').show();if(this.inCategoryPages){if(e){var curCatPage=document.getElementById('question-'+WatuPRO.current_question).closest('.watupro_catpage').id;if(typeof curCatPage=='undefined')return false;curCatPage=curCatPage.replace('catDiv','');this.curCatPage=parseInt(curCatPage)}
var numPages=jQuery('.watupro_catpage').length;this.curCatPage+=1;this.nextCategory(numPages,false,true,true,qPaginator);}
if(!WatuPRO.dontScroll&&qPaginator){jQuery('html, body').animate({scrollTop:jQuery('#questionWrap-'+j).offset().top-50},1000);}}
WatuPRO.ansGoto=function(e,j){jQuery('ul.watupro-answers-paginator li.active').removeClass('active');jQuery('#WatuPROAnswerPagination'+j).addClass('active');jQuery('div.watupro-paginated-answer').hide();jQuery('#watuPROPaginatedAnswer-'+j).show();if(jQuery("#watuproPaginatedAnswersStart").position()&&!WatuPRO.dontScroll){if(jQuery("#watuproPaginatedAnswersStart").position().top<jQuery(window).scrollTop()){jQuery('html,body').animate({scrollTop:jQuery("#watuproPaginatedAnswersStart").position().top},500);}
else if(jQuery("#watuproPaginatedAnswersStart").position().top+jQuery("#watuproPaginatedAnswersStart").height()>jQuery(window).scrollTop()+(window.innerHeight||document.documentElement.clientHeight)){jQuery('html,body').animate({scrollTop:jQuery("#watuproPaginatedAnswersStart").position().top-(window.innerHeight||document.documentElement.clientHeight)+jQuery("#watuproPaginatedAnswersStart").height()+15},500);}}}
WatuPRO.scrollTo=function(id,j){var questionID=jQuery("#qID_"+WatuPRO.current_question).val();var isAnswered=this.isAnswered(questionID);this.hilitePage(j,isAnswered);jQuery('html, body').animate({scrollTop:jQuery("#"+id).offset().top-150},1000);}
WatuPRO.hilitePage=function(j,isAnswered,dontRewindPaginator){dontRewindPaginator=dontRewindPaginator||null;if(jQuery('ul.watupro-question-paginator').length>0){if(isAnswered){jQuery('ul.watupro-question-paginator li.active').removeClass('unanswered');jQuery('ul.watupro-question-paginator li.active').addClass('answered');}else{jQuery('ul.watupro-question-paginator li.active').addClass('unanswered');jQuery('ul.watupro-question-paginator li.active').removeClass('answered');}
jQuery('ul.watupro-question-paginator li.active').removeClass('active');jQuery('#WatuPROPagination'+j).addClass('active');if(!dontRewindPaginator){this.currentDecade=Math.ceil(this.current_question/this.perDecade);var num=jQuery('ul.watupro-question-paginator li').length-2;var numDecades=Math.ceil(num/this.perDecade);jQuery('.watupro-paginator li').not('.watupro-category-paginator li').hide();if(this.currentDecade!=1)jQuery('.watupro-paginator li.rewind-down').show();if(this.currentDecade!=numDecades)jQuery('.watupro-paginator li.rewind-up').show();jQuery('.watupro-paginator li.decade-'+this.currentDecade).show();}}
if(jQuery('#watuPROCatPaginator'+this.exam_id).length>0&&jQuery('#questionCatTabInfo'+j).length>0){pageTabClassNum=jQuery('#questionCatTabInfo'+j).html();jQuery('#watuPROCatPaginator'+this.exam_id+' li').removeClass('active');jQuery('.WatuPROCatPaginationCatID'+pageTabClassNum).addClass('active');}}
WatuPRO.hilitePaginator=function(numQuestions){var dontRewindPaginator=true;for(i=1;i<=numQuestions;i++){var questionID=jQuery("#qID_"+i).val();var isAnswered=this.isAnswered(questionID);if(i+1>=numQuestions)dontRewindPaginator=false;this.hilitePage(i+1,isAnswered,dontRewindPaginator);}}
WatuPRO.movePaginator=function(dir,num){if(this.currentDecade==0){this.currentDecade=Math.ceil(this.current_question/this.perDecade);}
if(dir=='up')this.currentDecade++;else if(this.currentDecade>1)this.currentDecade--;var numDecades=Math.ceil(num/this.perDecade);jQuery('.watupro-paginator li').not('.watupro-category-paginator li').hide();if(this.currentDecade!=1)jQuery('.watupro-paginator li.rewind-down').show();if(this.currentDecade!=numDecades)jQuery('.watupro-paginator li.rewind-up').show();jQuery('.watupro-paginator li.decade-'+this.currentDecade).show();}
WatuPRO.submitResult=function(e){var okToSubmit=true;this.curCatPage=this.curCatPage||1;if(this.examMode==0&&this.total_questions>this.current_question)okToSubmit=false;if(this.examMode==2&&this.curCatPage<this.numCats)okToSubmit=false;if(!WatuPRO.forceSubmit){try{if(!watuproCheckPendingReview())return false;}
catch(err){};var numMarked=jQuery('#quiz-'+WatuPRO.exam_id+' .watupro-mark-review.marked').length;if(numMarked>0){}}
if(!WatuPRO.forceSubmit&&!okToSubmit&&(!WatuPRO.dontPromtNotlastpage&&!confirm(watupro_i18n.not_last_page)))return false;if(!WatuPRO.forceSubmit&&okToSubmit&&WatuPRO.confirmOnSubmit){if(!confirm(watupro_i18n.confirm_submit))return false;}
if(!WatuPRO.forceSubmit){for(let i=0;i<WatuPRO.requiredIDs.length;i++){if(!this.isAnswered(WatuPRO.requiredIDs[i])){let msg='';let qid=jQuery('.watupro-question-id-'+WatuPRO.requiredIDs[i]).attr('id');let numParts=qid.split('-');let numQ=numParts[1];if(jQuery('.watupro-minsel-id-'+WatuPRO.requiredIDs[i]).length>0){let minSels=WatuPRO.countMinSels(WatuPRO.requiredIDs[i]);msg=watupro_i18n.missed_required_question_num_min_sel.replace('{{min-selections}}',minSels);msg=msg.replace('%s',numQ);}
else msg=watupro_i18n.missed_required_question_num;msg=msg.replace('%s',numQ);alert(msg);return false;}}}
if(!WatuPRO.forceSubmit&&(e&&e.no_ajax&&e.no_ajax.value==1)&&jQuery('.watupro-file-upload').length>0){var sizeErrors=[];var extErrors=[];var maxUpload=WatuPRO.maxUpload*1024;var allowedTypes=WatuPRO.uploadExts.split(',');jQuery('.watupro-file-upload').each(function(i,fld){if(typeof fld.files[0]==='undefined')return true;var fldID=fld.id;var parts=fldID.split('-');var qNum=parts[1];if(fld.files[0].size>maxUpload)sizeErrors.push(qNum);var parts=fld.files[0].name.split('.');var ext=parts.pop();ext=ext.toLowerCase();if(jQuery.inArray(ext,allowedTypes)==-1)extErrors.push(qNum);});if(sizeErrors.length>0){var qNumbers=sizeErrors.join(', ');var alertMsg=watupro_i18n.size_errors.replace('%s',qNumbers);alertMsg=alertMsg.replace('%d',WatuPRO.maxUpload);alert(alertMsg);return false;}
if(extErrors.length>0){var qNumbers=extErrors.join(', ');var alertMsg=watupro_i18n.extension_errors.replace('%s',qNumbers);alert(alertMsg);return false;}}
if(jQuery('#WTPReCaptcha').length&&!jQuery('#WTPReCaptcha').is(':visible')&&!WatuPRO.forceSubmit){alert(watupro_i18n.complete_captcha);jQuery('#WTPReCaptcha').show();return false;}
if(jQuery('#WatuPROTextCaptcha').length&&!jQuery('#WatuPROTextCaptcha').is(':visible')&&!WatuPRO.forceSubmit){alert(watupro_i18n.complete_text_captcha);jQuery('#WatuPROTextCaptcha').show();return false;}
if(!this.validateEmailName())return false;if(jQuery('#timerDiv').length>0){jQuery('#timerDiv').hide();clearTimeout(WatuPRO.timerID);}
jQuery('#quiz-'+WatuPRO.exam_id).hide();jQuery('#submittingExam'+WatuPRO.exam_id).show();jQuery('html, body').animate({scrollTop:jQuery('#watupro_quiz').offset().top-50},1000);jQuery("#action-button").val(watupro_i18n.please_wait);jQuery("#action-button").attr("disabled",true);var data={"action":'watupro_submit',"quiz_id":this.exam_id,'question_id[]':this.qArr,"watupro_questions":jQuery('#quiz-'+this.exam_id+' input[name=watupro_questions]').val(),"post_id":this.post_id};data=this.completeData(data);data['start_time']=jQuery('#startTime').val();if(e&&e.no_ajax&&e.no_ajax.value==1)return true;if(jQuery('#WTPReCaptcha').length>0){jQuery('#quiz-'+WatuPRO.exam_id).show();data['recaptcha_challenge_field']=jQuery('#quiz-'+WatuPRO.exam_id+' input[name=recaptcha_challenge_field]').val();data['recaptcha_response_field']=jQuery('#quiz-'+WatuPRO.exam_id+' input[name=recaptcha_response_field]').val();data['g-recaptcha-response']=document.querySelector('.g-recaptcha-response').value;}
if(jQuery('#WatuPROTextCaptcha').length>0){jQuery('#quiz-'+WatuPRO.exam_id).show();data['watupro_text_captcha_answer']=jQuery('#quiz-'+WatuPRO.exam_id+' input[name=watupro_text_captcha_answer]').val();data['watupro_text_captcha_question']=jQuery('#quiz-'+WatuPRO.exam_id+' input[name=watupro_text_captcha_question]').val();}
if(jQuery('#watuPROAppID'+WatuPRO.exam_id).length>0){jQuery('#quiz-'+WatuPRO.exam_id).show();}
data['in_ajax']=1;if(!e||!e.no_ajax||e.no_ajax.value!=1){try{jQuery.ajax({"type":'POST',"url":this.siteURL,"data":data,"success":WatuPRO.success,"error":WatuPRO.errHandle,"cache":false,dataType:"text"});}catch(err){alert(err)}}}
WatuPRO.completeData=function(data){for(x=0;x<WatuPRO.qArr.length;x++){var questionID=WatuPRO.qArr[x];var ansgroup='.answerof-'+WatuPRO.qArr[x];var fieldName='answer-'+WatuPRO.qArr[x];var ansvalues=[];var i=0;var answerType=jQuery('#answerType'+questionID).val();if(answerType=='textarea'){if(jQuery('#textarea_q_'+WatuPRO.qArr[x]).attr('class')=='wp-editor-area'){ansvalues[0]=tinyMCE.get('textarea_q_'+WatuPRO.qArr[x]).getContent()}
else ansvalues[0]=jQuery('#textarea_q_'+WatuPRO.qArr[x]).val();let audioData=jQuery('#watuproAudioData'+questionID).val();data['audio_'+questionID]=audioData;}
else{jQuery(ansgroup).each(function(){if(jQuery(this).is(':checked')||jQuery(this).is(':selected')||answerType=='gaps'||answerType=='sort'||answerType=='matrix'||answerType=='nmatrix'||answerType=='slider'){ansvalues[i]=this.value;i++;}
if(jQuery(this).is(':checked')||jQuery(this).is(':selected')){var parts=this.id.split('-');var choiceID=parts[2];data['freetext_'+choiceID]=jQuery('#watuPROFreeText'+choiceID).val();}});}
data[fieldName+'[]']=ansvalues;if(jQuery('#watuproUserFeedback'+questionID).length){var feedback=jQuery('#watuproUserFeedback'+questionID).val();data['feedback-'+questionID]=feedback;}
var hints='';if(jQuery('#questionHints'+questionID).length)hints=jQuery('#questionHints'+questionID).html();data['question_'+questionID+'_hints']=hints;if(jQuery('#watuPRORatingWidget'+questionID).length){data['question_rating_'+questionID]=jQuery('#watuPRORatingWidget'+questionID+'-val').val();}}
if(jQuery('#watuproTakerEmail'+WatuPRO.exam_id).length)data['taker_email']=jQuery('#watuproTakerEmail'+WatuPRO.exam_id).val();if(jQuery('#watuproTakerName'+WatuPRO.exam_id).length)data['taker_name']=jQuery('#watuproTakerName'+WatuPRO.exam_id).val();if(jQuery('#watuproTakerPhone'+WatuPRO.exam_id).length)data['taker_phone']=jQuery('#watuproTakerPhone'+WatuPRO.exam_id).val();if(jQuery('#watuproTakerCompany'+WatuPRO.exam_id).length)data['taker_company']=jQuery('#watuproTakerCompany'+WatuPRO.exam_id).val();if(jQuery('#watuproTakerField1'+WatuPRO.exam_id).length)data['taker_field1']=jQuery('#watuproTakerField1'+WatuPRO.exam_id).val();if(jQuery('#watuproTakerField2'+WatuPRO.exam_id).length)data['taker_field2']=jQuery('#watuproTakerField2'+WatuPRO.exam_id).val();data['h_app_id']='_'+jQuery('#watuPROAppSourceID'+WatuPRO.exam_id).val();if(WatuPRO.premature_end==1)data['premature_end']=1;data['wtpuc_ok']=WatuPRO.userChoice;if(WatuPRO.custom_data)data['custom_data']=WatuPRO.custom_data;if(WatuPRO.autoSubmitted)data['auto_submitted']=1;if(jQuery('#watuproEvaluateOnTheFly'+WatuPRO.exam_id).length)data['evaluate_on_the_fly']=1;return data;}
WatuPRO.success=function(r){if(r.indexOf('WATUPRO_CAPTCHA:::')>-1){parts=r.split(":::");alert(parts[1]);jQuery("#action-button").val(watupro_i18n.try_again);jQuery("#action-button").removeAttr("disabled");return false;}
jQuery("#action-button").removeAttr("disabled");if(r.indexOf('WATUPRO_REDIRECT:::')>-1){parts=r.split(":::");window.location=parts[1];return true;}
jQuery('#watupro_quiz').html(r);jQuery('#watupro_quiz').addClass('watupro-completed');if(jQuery('#watupro-modal').length){jQuery('#watupro-modal').dialog();}
if(typeof MathJax!='undefined'){if(typeof MathJax.Hub!='undefined')MathJax.Hub.Queue(["Typeset",MathJax.Hub,"watupro_quiz"]);MathJax.typeset();}
if(watupro_i18n.disable_copy==1){jQuery('#watupro_quiz').bind("cut copy",function(e){e.preventDefault();});jQuery('#watupro_quiz').bind("contextmenu",function(e){e.preventDefault();});}
jQuery('.wtpsd-category-tabs').hide();if(r.indexOf('<!--watupro-tracker')!==-1){parts=r.split('<!--watupro-tracker');var cParts=parts[1].split('-->');parts[1]=cParts[0];trackCode=parts[1].trim();parts=trackCode.split('|||');if(typeof WTPTracker.track==="function"){WTPTracker.track(parts[0],parts[1],parts[2],parts[3]);}}}
WatuPRO.errHandle=function(xhr,msg){var statusErrorMap={'400':"Server understood the request, but request content was invalid.",'401':"Unauthorized access.",'403':"Forbidden resource can't be accessed.",'500':"Internal server error.",'503':"Service unavailable.",'parsererror':'Requested JSON parse failed.','timeout':'Request timed out.','abort':'Ajax request aborted.',};if(xhr.status){msg+="("+statusErrorMap[xhr.status]+")";}
jQuery('#watupro_quiz').html('Error Occurred:'+msg+" "+xhr.statusText);jQuery("#action-button").val(watupro_i18n.try_again);jQuery("#action-button").removeAttr("disabled");}
WatuPRO.maybeHideNext=function(){if(typeof(WatuPROSettings[this.exam_id])!=='undefined'&&WatuPROSettings[this.exam_id].singleChoiceAction=='next'&&WatuPROSettings[this.exam_id].singleChoiceActionHideNext==1){if(jQuery('.answerTypeCnt'+WatuPRO.current_question).val()=='radio')jQuery("#next-question").addClass("watupro-hidden");}}
WatuPRO.initWatu=function(){WatuPRO.total_questions=jQuery(".watu-question").length;if(!WatuPRO.pagePreLoaded){this.hilitePage(this.current_question,false);WatuPRO.maybeHideNext();}
else{WatuPRO.goto(null,WatuPRO.current_question);}
var questionID=WatuPRO.qArr[WatuPRO.current_question-1];if(jQuery('#watuproMemory'+questionID).length>0&&jQuery('#watuproMemory'+questionID).is(":visible")){WatuPRO.showingMemory(questionID);}
else{if(jQuery('#chainActButton'+WatuPRO.exam_id)==null)jQuery('.watupro_buttons').show();}
if(WatuPRO.total_questions==1){jQuery("#next-question").addClass("watupro-hidden");jQuery("#prev-question").addClass("watupro-hidden");jQuery("#show-answer").hide();}else{}
jQuery('.watupro-paginator-wrap').show();var quizID=WatuPRO.exam_id;if(jQuery('#watuPROAppID'+quizID).length>0){WatuPRO.hAppID='_'+jQuery('#watuPROAppSourceID'+quizID).val();jQuery('#watuPROAppID'+quizID).val(WatuPRO.hAppID);}
if(watupro_i18n.disable_copy==1){jQuery('.quiz-form').bind("cut copy",function(e){e.preventDefault();});jQuery('.quiz-form').bind("contextmenu",function(e){e.preventDefault();});}
if(typeof(WatuPROSettings[quizID])=='undefined')return true;if(WatuPROSettings[quizID].singleChoiceAction=='show'||WatuPROSettings[quizID].singleChoiceAction=='next'){jQuery('#quiz-'+quizID+' input[type=radio].answer').click(function(e){var classes=jQuery(this).attr('class');var parts=classes.split(' ');for(i=0;i<parts.length;i++){if(parts[i].indexOf('answerof-')>-1){var sparts=parts[i].split('-');var questionID=sparts[1];var par=jQuery(this).closest('div[class^="watu-question"]');var wrapID=jQuery(par).attr("id");var qparts=wrapID.split('-');var curQues=qparts[1];if(WatuPROSettings[quizID].singleChoiceAction=='show')return WatuPRO.liveResult(questionID,curQues);if(WatuPROSettings[quizID].singleChoiceAction=='next'&&!WatuPRO.inCategoryPages){if(curQues>=WatuPRO.qArr.length){WatuPRO.submitResult(e);return true;}
WatuPRO.current_question=curQues;WatuPRO.nextQuestion(e);return true;}}}});}}
WatuPRO.takingDetails=async function(id){var w=window.innerWidth*.6;var h=window.innerHeight*.85;w=parseInt(w);h=parseInt(h);let promise=new Promise((resolve,reject)=>{var res=tb_show(watupro_i18n.taking_details,watupro_i18n.ajax_url+"?action=watupro_taking_details&width="+w+"&height="+h+"&id="+id,watupro_i18n.ajax_url);setTimeout(()=>resolve("done!"),1500);});let mathjaxload=await promise;if(mathjaxload){if(typeof MathJax!='undefined')MathJax.typeset();}}
WatuPRO.nextCategory=function(numCats,dir,noHiliteQuestion,dontCheckRequired,qPaginator){this.curCatPage=this.curCatPage||1;noHiliteQuestion=noHiliteQuestion||0;dontCheckRequired=dontCheckRequired||0;qPaginator=qPaginator||null;if(!WatuPRO.forceSubmit&&!dontCheckRequired&&dir){for(let i=0;i<WatuPRO.requiredIDs.length;i++){if(!jQuery('#catDiv'+this.curCatPage+' #watupro-required-question-'+WatuPRO.requiredIDs[i]).length)continue;if(!this.isAnswered(WatuPRO.requiredIDs[i])){var msg=watupro_i18n.missed_required_question_num;var qid=jQuery('.watupro-question-id-'+WatuPRO.requiredIDs[i]).attr('id');var numParts=qid.split('-');var numQ=numParts[1];msg=msg.replace('%s',numQ);alert(msg);return false;}}}
this.stopAudios();if(dir)this.curCatPage++;else this.curCatPage--;jQuery('.watupro_catpage').hide();jQuery('#catDiv'+this.curCatPage).show();jQuery('#catDiv'+this.curCatPage+' .watu-question').each(function(i,elt){jQuery(elt).show();});if(this.curCatPage>=numCats){jQuery('#watuproNextCatButton').hide();jQuery('#action-button').show();if(jQuery('#WTPReCaptcha').length)jQuery('#WTPReCaptcha').show();if(jQuery('#WatuPROTextCaptcha').length)jQuery('#WatuPROTextCaptcha').show();}
else{jQuery('#watuproNextCatButton').show();if(jQuery('#WTPReCaptcha').length)jQuery('#WTPReCaptcha').hide();if(jQuery('#WatuPROTextCaptcha').length)jQuery('#WatuPROTextCaptcha').hide();}
if(this.curCatPage<=1)jQuery('#watuproPrevCatButton').hide();else jQuery('#watuproPrevCatButton').show();if(!WatuPRO.dontScroll&&!qPaginator){jQuery('html, body').animate({scrollTop:jQuery('#watupro_quiz').offset().top-50},1000);}
WatuPRO.progressBar(this.curCatPage,WatuPRO.exam_id);if(jQuery('ul.watupro-paginator').length&&!noHiliteQuestion){var curQuestionDiv=jQuery("#catDiv"+this.curCatPage+" div.watu-question:first").attr('id');var parts=curQuestionDiv.split('-');var qNum=parts[1];jQuery('ul.watupro-paginator li.active').removeClass('active');jQuery('#WatuPROPagination'+qNum).addClass('active');}
jQuery('ul#WatuPROCatPaginator'+WatuPRO.exam_id+' li').removeClass('active');jQuery('li.watupro-cat-pagination-page-'+this.curCatPage).addClass('active');if(this.store_progress)this.saveResult(false);}
WatuPRO.liveResult=function(questionID,curQues){questionID=questionID||null;curQues=curQues||null;if(!questionID)questionID=jQuery("#qID_"+WatuPRO.current_question).val();if(!curQues)curQues=WatuPRO.current_question;if(!WatuPRO.isAnswered(questionID)&&typeof WatuPRO.LiveResultNoAnswer=='undefined'){alert(watupro_i18n.please_answer);return false;}
jQuery('#questionWrap-'+curQues).hide();jQuery('#liveResult-'+curQues).css('min-height',jQuery('#questionWrap-'+curQues).height()+'px');jQuery('#liveResult-'+curQues).show();if(curQues)jQuery('.liveResultBtn'+curQues).hide();jQuery('#liveResultBtn').hide();var numHints=jQuery('#questionHints'+questionID+' .watupro-hint').length;var data={"action":'watupro_liveresult',"quiz_id":WatuPRO.exam_id,'question_id':questionID,'num_hints_used':numHints,'question_num':curQues,"watupro_questions":jQuery('#quiz-'+WatuPRO.exam_id+' input[name=watupro_questions]').val()};data=WatuPRO.completeData(data);jQuery.post(WatuPRO.siteURL,data,function(msg){jQuery('#liveResult-'+curQues).html(msg);if(jQuery('#liveResBtn-'+questionID).length>0)jQuery('#liveResBtn-'+questionID).hide();if(typeof MathJax!='undefined'){if(typeof MathJax.Hub!='undefined')MathJax.Hub.Queue(["Typeset",MathJax.Hub,"liveResult-"+curQues]);MathJax.typeset();}
try{watuproUnmarkReview(questionID);}catch(err){};});}
WatuPRO.maxSelections=function(id,num,chk){var cnt=jQuery(".answerof-"+id+":checked").length;if(cnt>num){chk.checked=false;return false;}
return true;}
WatuPRO.saveResult=function(e){var curCatPage=0;if(typeof(this.curCatPage)!='undefined')curCatPage=this.curCatPage;data={'action':'watupro_store_all','question_ids':this.qArr,"exam_id":this.exam_id,'watupro_questions':jQuery('#quiz-'+this.exam_id+' input[name=watupro_questions]').val(),'current_question':this.current_question,'current_catpage':curCatPage};var startTime=jQuery('#startTime').val();if(startTime)data['start_time']=startTime;data=this.completeData(data);jQuery.post(WatuPRO.siteURL,data,function(msg){if(e)alert(watupro_i18n.selections_saved);});}
WatuPRO.getHints=function(qid){var numHints=jQuery('#questionHints'+qid+' .watupro-hint').length;var numHintsTotal=jQuery('div.watupro-hint').length;data={'action':'watupro_get_hints','qid':qid,"exam_id":this.exam_id,"num_hints":numHints,"num_hints_total":numHintsTotal};jQuery.post(WatuPRO.siteURL,data,function(msg){parts=msg.split("|WATUPRO|");if(parts[0]=='ERROR')alert(parts[1]);else jQuery('#questionHints'+qid).append(parts[1]);if(parts[2]&&parts[2]=='nomorehints')jQuery('#questionHintLink'+qid).hide();WatuPRO.saveResult(false);});}
WatuPRO.startButton=function(){if(!WatuPRO.validateEmailName(true))return false;if(jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-start').length&&jQuery('#quiz-'+WatuPRO.exam_id+' input[name=no_ajax]').length&&jQuery('#quiz-'+WatuPRO.exam_id+' input[name=no_ajax]').val()==1){jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-start input').each(function(i,fld){fld.type='hidden';jQuery('#quiz-'+WatuPRO.exam_id).append(fld);});jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-start select').each(function(i,fld){fld.type='hidden';fld.style.display='none';jQuery('#quiz-'+WatuPRO.exam_id).append(fld);});}
if(jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-start').length&&WatuPRO.takingsByEmail){data={'action':'watupro_ajax',"exam_id":this.exam_id,'do':'takings_by_email',"email":jQuery('#watuproTakerEmail'+this.exam_id).val(),'allowed_attempts':WatuPRO.takingsByEmail};jQuery.post(WatuPRO.siteURL,data,function(msg){parts=msg.split("|WATUPRO|");if(parts[0]=='ERROR'){alert(parts[1]);jQuery('#quiz-'+WatuPRO.exam_id).hide();jQuery('#description-quiz-'+WatuPRO.exam_id).show();return false;}});}
jQuery('#quiz-'+this.exam_id).show();jQuery('#description-quiz-'+this.exam_id).hide();if(!WatuPRO.dontScrollStart&&jQuery(document).scrollTop()>250){jQuery('html, body').animate({scrollTop:jQuery('#watupro_quiz').offset().top-100},500);}
let questionID=jQuery("#qID_"+WatuPRO.current_question).val();if(jQuery('#watuproMemory'+questionID).length>0&&jQuery('#watuproMemory'+questionID).is(":visible")){WatuPRO.showingMemory(questionID);}
if(typeof WatuPROTrackStart!='undefined'&&WatuPROTrackStart!=null){WTPTracker.track(WatuPROTrackStart.category,WatuPROTrackStart.action,WatuPROTrackStart.label,WatuPROTrackStart.value);}}
WatuPRO.validateEmailName=function(skipAutoGenerated){if(WatuPRO.forceSubmit)return true;jQuery('.watupro-contact-error').html('');if(jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-end').length){if(skipAutoGenerated)return true;if(jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-end').is(':hidden')){if(this.examMode==0)this.current_question=this.total_questions;if(this.examMode==2)this.curCatPage=this.numCats;jQuery('#quiz-'+WatuPRO.exam_id+' .watupro-paginator-wrap').hide();jQuery('#quiz-'+WatuPRO.exam_id+' div.watu-question').hide();jQuery('#quiz-'+WatuPRO.exam_id+' input[type=button]').not('#action-button').hide();jQuery('#quiz-'+WatuPRO.exam_id+' div.watupro_catpage h3').hide();jQuery('#quiz-'+WatuPRO.exam_id+' div.watupro_catpage').hide();jQuery('#prev-question').addClass("watupro-hidden");jQuery('#watuproPrevCatButton').hide();jQuery('.watu-question').hide();jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-end').show('slow');jQuery('html,body').animate({scrollTop:jQuery('#watuproContactDetails-'+WatuPRO.exam_id+'-end').offset().top-50},'slow');return false;}}
var skipAutoGenerated=skipAutoGenerated|false;if(jQuery('#watuproTakerEmail'+WatuPRO.exam_id).length){var emailVal=jQuery('#watuproTakerEmail'+WatuPRO.exam_id).val();wronglyEmpty=notEmptyInvalid=false;if((emailVal==''&&!this.emailIsNotRequired&&!jQuery('#watuproTakerEmail'+WatuPRO.exam_id).hasClass('optional')))wronglyEmpty=true;if(emailVal!=''&&(emailVal.indexOf('@')<0||emailVal.indexOf('.')<1))notEmptyInvalid=true;if((wronglyEmpty||notEmptyInvalid)&&(!skipAutoGenerated||!jQuery('#watuproTakerEmail'+WatuPRO.exam_id).hasClass('watupro-autogenerated'))){jQuery('#watuproTakerEmailError'+WatuPRO.exam_id).html(watupro_i18n.email_required);jQuery('#watuproTakerEmail'+WatuPRO.exam_id).focus();return false;}}
if(jQuery('#watuproTakerName'+WatuPRO.exam_id).length){var nameVal=jQuery('#watuproTakerName'+WatuPRO.exam_id).val();if(nameVal==''&&!jQuery('#watuproTakerName'+WatuPRO.exam_id).hasClass('optional')){jQuery('#watuproTakerNameError'+WatuPRO.exam_id).html(watupro_i18n.name_required);jQuery('#watuproTakerName'+WatuPRO.exam_id).focus();return false;}}
var canSubmit=true;jQuery('div.watupro-ask-for-contact-quiz-'+WatuPRO.exam_id+' input.watupro-contact-required').each(function(i,obj){if(obj.type=='checkbox'){if(!obj.checked){jQuery('#'+obj.id+'Error').html(watupro_i18n.field_required);}}
if((obj.type=='text'&&obj.value=='')||(obj.type=='checkbox'&&!obj.checked)){jQuery('#'+obj.id+'Error').html(watupro_i18n.field_required);obj.focus();canSubmit=false;return false;}});if(!canSubmit)return false;return true;}
WatuPRO.stopAudios=function(){var audios=jQuery(".watu-question audio");if(audios){var i;for(i=0;i<audios.length;i++){audios[i].pause();}}}
WatuPRO.progressBar=function(pageNum,examID){let varWidth=0;if(this.progressBarMode=='pages'){if(jQuery('#watupro-progress-bar-'+examID).length==0)return true;barWidth=Math.round(100*(pageNum-1)/jQuery('#watupro-progress-bar-pages-'+examID).val());}
else{let totalQ=numAnswered=0;jQuery('.watupro-question-id').each(function(i,elt){totalQ++;if(WatuPRO.isAnswered(elt.value))numAnswered++;});barWidth=totalQ?Math.round(100*numAnswered/totalQ):0;}
jQuery('#watupro-progress-bar-'+examID).animate({width:barWidth+'%'},500);if(jQuery('#watupro-progress-bar-percent-'+examID).length){jQuery('#watupro-progress-bar-percent-'+examID).html(barWidth+'%');}}
WatuPRO.unselect=function(btn,questionID){jQuery('.answerof-'+questionID).removeAttr('checked');jQuery(btn).hide();}
WatuPRO.showHideUnselect=function(chk,questionID){if(chk.checked)jQuery('#watuPROUnselect-'+questionID).show();else{var anyChecked=false;jQuery('.answerof-'+questionID).each(function(i,chk){if(chk.checked)anyChecked=true;});if(anyChecked)jQuery('#watuPROUnselect-'+questionID).show();else jQuery('#watuPROUnselect-'+questionID).hide();}}
WatuPRO.paginateAnswersTable=function(dir,cnt,perDecade){jQuery('.answers-decade-'+WatuPRO.currentAnswersDecade).hide();if(dir=='next'){WatuPRO.currentAnswersDecade++;jQuery('.answers-decade-'+WatuPRO.currentAnswersDecade).show();jQuery('#WatuPROanswersTablePrevLink').show();if(cnt<=WatuPRO.currentAnswersDecade*perDecade)jQuery('#WatuPROanswersTableNextLink').hide();}
if(dir=='prev'){WatuPRO.currentAnswersDecade--;jQuery('.answers-decade-'+WatuPRO.currentAnswersDecade).show();jQuery('#WatuPROanswersTableNextLink').show();if(WatuPRO.currentAnswersDecade==1)jQuery('#WatuPROanswersTablePrevLink').hide();}
if(!isNaN(dir)){WatuPRO.currentAnswersDecade=dir;jQuery('.answers-decade-'+WatuPRO.currentAnswersDecade).show();if(cnt<=WatuPRO.currentAnswersDecade*perDecade)jQuery('#WatuPROanswersTableNextLink').hide();else jQuery('#WatuPROanswersTableNextLink').show();if(WatuPRO.currentAnswersDecade==1)jQuery('#WatuPROanswersTablePrevLink').hide();else jQuery('#WatuPROanswersTablePrevLink').show();}}
WatuPRO.FBShare=function(url,title,desc,picture){var quote='';quote=decodeURI(title)+"\n"+decodeURIComponent(desc);FB.ui({method:'share',href:url,quote:quote,},function(response){});}
WatuPRO.showingMemory=function(questionID){jQuery('.watupro_buttons').hide();var classes=document.getElementById('watuproMemory'+questionID).className.split(/\s+/);seconds=1;for(i=0;i<classes.length;i++){if(classes[i].indexOf('watupro-memory-seconds')>-1){var parts=classes[i].split('-');seconds=parts[3];}}
WatuPRO.memoryTimerID=self.setTimeout("WatuPRO.HideMemory("+questionID+")",seconds*1000);}
WatuPRO.ShowDistraction=function(questionID){let distraction=jQuery('#wtpDistraction-'+questionID).html();jQuery('#watuproMemory'+questionID).html(distraction);clearTimeout(WatuPRO.memoryTimerID);}
WatuPRO.HideMemory=function(questionID){jQuery('#watuproMemory'+questionID).hide();jQuery('#watuproMemoryContents'+questionID).show();jQuery('#questionChoices'+questionID).show();jQuery('.watupro_buttons').show();clearTimeout(WatuPRO.memoryTimerID);}
WatuPRO.InitializeTimer=function(timeLimit,examID,showQuestions){if(showQuestions&&!WatuPRO.validateEmailName(true))return false;if(typeof WatuPROTrackStart!='undefined'&&WatuPROTrackStart!=null){WTPTracker.track(WatuPROTrackStart.category,WatuPROTrackStart.action,WatuPROTrackStart.label,WatuPROTrackStart.value);}
if(showQuestions){jQuery('#watuproTimerForm'+examID+' input[name=watupro_start_timer]').val(1);if(jQuery('#watuproTakerEmail'+WatuPRO.exam_id).length)jQuery('#watuproTimerForm'+examID+' input[name=watupro_taker_email]').val(jQuery('#watuproTakerEmail'+WatuPRO.exam_id).val());if(jQuery('#watuproTakerName'+WatuPRO.exam_id).length)jQuery('#watuproTimerForm'+examID+' input[name=watupro_taker_name]').val(jQuery('#watuproTakerName'+WatuPRO.exam_id).val());if(jQuery('#watuproTakerPhone'+WatuPRO.exam_id).length)jQuery('#watuproTimerForm'+examID+' input[name=watupro_taker_phone]').val(jQuery('#watuproTakerPhone'+WatuPRO.exam_id).val());if(jQuery('#watuproTakerCompany'+WatuPRO.exam_id).length)jQuery('#watuproTimerForm'+examID+' input[name=watupro_taker_company]').val(jQuery('#watuproTakerCompany'+WatuPRO.exam_id).val());if(jQuery('#watuproTakerField1'+WatuPRO.exam_id).length)jQuery('#watuproTimerForm'+examID+' input[name=watupro_taker_field1]').val(jQuery('#watuproTakerField1'+WatuPRO.exam_id).val());if(jQuery('#watuproTakerField2'+WatuPRO.exam_id).length)jQuery('#watuproTimerForm'+examID+' input[name=watupro_taker_field2]').val(jQuery('#watuproTakerField2'+WatuPRO.exam_id).val());if(jQuery('#watuproTakerCheckbox'+WatuPRO.exam_id).length)jQuery('#watuproTimerForm'+examID+' input[name=watupro_taker_checkbox]').val(jQuery('#watuproTakerCheckbox'+WatuPRO.exam_id).val());document.getElementById('watuproTimerForm'+examID).submit();return false;}
WatuPRO.startedTime=jQuery('#startTimeStamp').val();if(timeLimit>0){data={exam_id:WatuPRO.exam_id,'action':'watupro_initialize_timer'};jQuery.post(WatuPRO.siteURL,data,function(msg){parts=msg.split("<!--WATUPRO_TIME-->");var d=new Date();d.setTime(d.getTime()+(24*3600*1000));var expires="expires="+d.toUTCString();document.cookie="start_time"+WatuPRO.exam_id+"="+parts[1]+";"+expires+";path=/";jQuery('#startTime').val(parts[1]);WatuPRO.startedTime=parts[1];if(WatuPRO.timerAdjustedBySchedule)WatuPRO.startedTime=parts[2];WatuPRO.currentTime=parts[2];});}
WatuPRO.secs=timeLimit;WatuPRO.StopTheClock();WatuPRO.StartTheTimer();if(!this.autoSubmitted)WatuPRO.saveResult(false);jQuery('html, body').animate({scrollTop:jQuery("#timerDiv").offset().top-100},500);}
WatuPRO.StopTheClock=function(){if(WatuPRO.timerRunning);clearTimeout(WatuPRO.timerID);WatuPRO.timerRunning=false;}
WatuPRO.pad=function(str,max){str=str.toString();return str.length<max?this.pad("0"+str,max):str;}
WatuPRO.StartTheTimer=function(){if(WatuPRO.secs<=0){WatuPRO.StopTheClock();document.getElementById('timerDiv').innerHTML="<h2 style='color:red';>"+watupro_i18n.time_over+"</h2>";WatuPRO.forceSubmit=true;WatuPRO.autoSubmitted=true;document.cookie="start_time"+WatuPRO.exam_id+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/";WatuPRO.submitResult();}
else{if(WatuPRO.secs<60)secsText=WatuPRO.secs+" "+watupro_i18n.seconds;else{var secondsLeft=Math.round(WatuPRO.secs%60);if(watupro_i18n.seconds=='')secondsLeft=WatuPRO.pad(secondsLeft,2);var mins=Math.round((WatuPRO.secs-secondsLeft)/60);if(mins<60){secsText=mins+watupro_i18n.minutes_and+secondsLeft+watupro_i18n.seconds;}
else{var minsLeft=mins%60;var hours=(mins-minsLeft)/60;if(watupro_i18n.minutes_and==':')minsLeft=WatuPRO.pad(minsLeft,2);secsText=hours+watupro_i18n.hours+minsLeft+watupro_i18n.minutes_and+secondsLeft+watupro_i18n.seconds;}}
document.getElementById('timerDiv').innerHTML=watupro_i18n.time_left+" "+secsText;if(WatuPRO.TimerTurnsRed&&WatuPRO.secs<=WatuPRO.TimerTurnsRed)document.getElementById('timerDiv').style.color='red';if(WatuPRO.jsTimeDiff==null){WatuPRO.jsTimeDiff=Date.now()-WatuPRO.currentTime*1000;}
var adjustedNow=Date.now()-WatuPRO.jsTimeDiff;var secsPassed=adjustedNow-WatuPRO.startedTime*1000;secsPassed=Math.floor(secsPassed/1000);WatuPRO.secs=WatuPRO.fullTimeLimit-secsPassed;WatuPRO.timerRunning=true;WatuPRO.timerID=self.setTimeout("WatuPRO.StartTheTimer()",500);}}
jQuery(window).on("load",function(){WatuPRO.initWatu();});document.addEventListener("DOMContentLoaded",function(){const recordButtons=document.querySelectorAll(".watupro-start-recording");const stopButtons=document.querySelectorAll(".watupro-stop-recording");const audioPreviews=document.querySelectorAll(".watupro-audio-preview");let mediaRecorders={};let audioChunks={};let previousAudioPaths={};recordButtons.forEach(button=>{button.addEventListener("click",async(event)=>{const quesID=event.target.id.replace("start-recording","");const stopButton=document.getElementById("stop-recording"+quesID);const audioPreview=document.getElementById("audio-preview"+quesID);try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mediaRecorder=new MediaRecorder(stream);mediaRecorders[quesID]=mediaRecorder;audioChunks[quesID]=[];mediaRecorder.ondataavailable=(event)=>{audioChunks[quesID].push(event.data);};mediaRecorder.onstop=async()=>{const audioBlob=new Blob(audioChunks[quesID],{type:"audio/webm"});const formData=new FormData();formData.append("audio",audioBlob,"response"+quesID+".webm");formData.append("question_id",quesID);formData.append("action","watupro_save_audio_response");if(previousAudioPaths[quesID]){formData.append("previous_audio_path",previousAudioPaths[quesID]);}
fetch(watupro_i18n.ajax_url,{method:"POST",body:formData}).then(response=>response.json()).then(data=>{if(data.success){fetch(data.data.audio_url).then(response=>{if(!response.ok)throw new Error(`HTTP error! Status: ${response.status}`);return response.blob();}).then(blob=>{const objectURL=URL.createObjectURL(blob);audioPreview.src=objectURL;audioPreview.style.display="block";}).catch(error=>console.error("Error loading audio:",error));audioPreview.style.display="block";document.getElementById('watuproAudioData'+quesID).value=JSON.stringify(data.data);previousAudioPaths[quesID]=data.data.audio_path;}else{alert("Could not save recording!");}});delete audioChunks[quesID];};mediaRecorder.start();button.disabled=true;stopButton.disabled=false;}catch(error){console.error("Media Device Error:",error);if(error.name==="NotFoundError"||error.name==="NotAllowedError"||error.name==="NotReadableError"){let errorMessage="To record an audio, please:";if(error.name==="NotFoundError"){errorMessage+="\n- Make sure you have a microphone connected";}else if(error.name==="NotAllowedError"){errorMessage+="\n- Allow microphone access";}else if(error.name==="NotReadableError"){errorMessage+="\n- If your microphone is used by another app, please close it";}
alert(errorMessage);}else{alert("We could not access your microphone.");}}});});stopButtons.forEach(button=>{button.addEventListener("click",(event)=>{const quesID=event.target.id.replace("stop-recording","");if(mediaRecorders[quesID]){mediaRecorders[quesID].stop();event.target.disabled=true;document.getElementById("start-recording"+quesID).disabled=false;}});});});